Name:           ros-hydro-iai-common-msgs
Version:        0.0.3
Release:        0%{?dist}
Summary:        ROS iai_common_msgs package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-hydro-data-vis-msgs
Requires:       ros-hydro-designator-integration-msgs
Requires:       ros-hydro-dna-extraction-msgs
Requires:       ros-hydro-iai-content-msgs
Requires:       ros-hydro-iai-kinematics-msgs
Requires:       ros-hydro-iai-robosherlock-actions
Requires:       ros-hydro-mln-robosherlock-msgs
Requires:       ros-hydro-saphari-msgs
Requires:       ros-hydro-scanning-table-msgs
Requires:       ros-hydro-sherlock-sim-msgs
BuildRequires:  ros-hydro-catkin

%description
Message definitions created and used by the Institute for Artificial
Intelligence research group at the University of Bremen

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Tue Oct 14 2014 AI Robotics <ai-robotics@cs.uni-bremen.de> - 0.0.3-0
- Autogenerated by Bloom

